version: '3'

services:
  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - app.env
      - superuser.env
    ports:
      - 8000:8000
    depends_on:
      - db
    entrypoint: /app/entrypoint.sh

volumes:
  db_data: